try {
} catch(error_used) {
    console.log(error_used);
}

try {
} catch(error) {
}

try {
} catch({message}) {
}

try {
} catch({stack, ...error}) {
}
