try {} catch (error_used) {
    console.log(error_used);
}

try {} catch {}

try {} catch ({}) {}

try {} catch ({}) {}
